### ISSUE TITLE
docksal 'fin project create' breaks in provus due to missing master branch

### ISSUE THREAD

**Issue by icasimpan** [promet/provus#49]
Hi @acouch 

Now that we started tagging, perhaps we can create a 'master' branch out of latest release.
That way, `fin project create` option to use a custom repository will work.

RIght now, it's broken due only to the absence of the master branch.

**Comment by acouch** [comment]
@icasimpan great to note. I created a ticket in Docksal: https://github.com/docksal/docksal/issues/1435. If they are willing to fix this we could keep ``develop``. I'm concerned about the overhead of maintaining ``master`` alongside develop and that it would likely confuse people.

**Comment by acouch** [comment]
Looks like they accepted the change! Lets update the documentation. Seems like a better way to create a new project.

**Comment by icasimpan** [comment]
Cool. Open source for the win, indeed. Closing ticket.
